### ISSUE TITLE
Failed to open file 'data/runsqlrun.gresource'

### ISSUE THREAD

**Issue by pkkid** [andialbrecht/runsqlrun#11]
Getting this error when running `python3 -m rsr`.  The file doesn't appear to exist.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mjs7231/Projects/runsqlrun/rsr/__main__.py", line 5, in <module>
    cmd.main()
  File "/home/mjs7231/Projects/runsqlrun/rsr/cmd.py", line 27, in main
    resource = Gio.resource_load('data/runsqlrun.gresource')
gi._glib.GError: Failed to open file 'data/runsqlrun.gresource': open() failed: No such file or directory
```

If it's at all applicable, the output of make is:

```
inkscape -z -f data/icons/runsqlrun.svg -w 128 -e data/icons/128x128/runsqlrun.png
Background RRGGBBAA: ffffff00
Area 0:0:248:248 exported to 128 x 128 pixels (46.4516 dpi)
Bitmap saved as: data/icons/128x128/runsqlrun.png
```

**Comment by andialbrecht** [comment]
You need to run `make compile-ressources` (which in turn requires "glib-compile-resources" to be installed).

I'd leave this issue open because I'm not sure what's the best thing to do here. Checking in generated files or depending on those tools when running from source.

**Comment by andialbrecht** [comment]
Changed my mind. Makefile works now as documented and README is updated to include glib-compile-resources :)
