### ISSUE TITLE
Error when copying a single cell

### ISSUE THREAD

**Issue by andialbrecht** [andialbrecht/runsqlrun#9]
The following exception occurs when a single cell is copied:

```
Traceback (most recent call last):
  File "/home/andi/devel/runsqlrun/rsr/worksheet/completion.py", line 116, in do_populate
    word = self._get_word(context)
  File "/home/andi/devel/runsqlrun/rsr/worksheet/completion.py", line 37, in _get_word
    start_iter = end_iter.copy()
AttributeError: 'tuple' object has no attribute 'copy'
```

Steps to reproduce:
- Highlight single cell in results view with mouse
- Hit Ctrl-C (copy)

**Comment by andialbrecht** [comment]
Fixed in 36cf6acfb97ad4f87bff69deb7622c8236c46183. This was actually a regression that was introduced in some GTK update.
